### ISSUE TITLE
补充

### ISSUE THREAD

**Issue by Wizardp007** [simplepeng/HeGuiChecker#1]
1. android.app.ApplicationPackageManager.getPackageInfoAsUser
2. android.app.ApplicationPackageManager.getInstallerPackageName

**Comment by simplepeng** [comment]
@Wizardp007 这两个方法感觉没有哪里说不合规的方法呀，倒是`getInstalledPackages`和`getInstalledApplications`可能为非法方法

**Comment by Wizardp007** [comment]
> @Wizardp007 这两个方法感觉没有哪里说不合规的方法呀，倒是`getInstalledPackages`和`getInstalledApplications`可能为非法方法

小米给出的违规记录中有

**Comment by simplepeng** [comment]
已添加到v1.0.2版本
