### ISSUE TITLE
补充

### ISSUE THREAD

**Issue by hellohejinyu** [simplepeng/HeGuiChecker#2]
获取剪切板也是违规的，小米会驳回。但是具体哪个方法我不知道。

![image](https://user-images.githubusercontent.com/8766034/206707982-de86c561-b6b4-40eb-9edd-3f27370ca751.png)

**Comment by hellohejinyu** [comment]
![image](https://user-images.githubusercontent.com/8766034/206714189-e3aa839a-2030-41dd-9bd4-3e1176fef7ba.png)

**Comment by simplepeng** [comment]
@hellohejinyu 已新增到`v1.0.3`版本
